### ISSUE TITLE
App Styling is poor

### ISSUE THREAD

**Issue by daas-ankur-shukla** [daas-ankur-shukla/SpeechToSign#14]
The styling of the application is poor. @bneogy92 any suggestions on that

**Comment by daas-ankur-shukla** [comment]
![img_20180306_030942__01](https://user-images.githubusercontent.com/20864366/37001284-0b470480-20ec-11e8-8172-5bd9076c6def.jpg)

how about this?

**Comment by bneogy92** [comment]
Good with me. How about moving the push button to the left? The point being the push button start recording voice. For someone looking at the above design for the 1st time. Seems like push generates images without voice.

**Comment by bneogy92** [comment]
@daas-ankur-shukla Welcome message as it is with the push button below it. The recognition status below push button. Gives a sequential flow to the UI.

**Comment by bneogy92** [comment]
As discussed, providing credits to Dr. Bill Vicars in the footers helps.

**Comment by daas-ankur-shukla** [comment]
Cool. Any suggestions for the credits line to Dr. Bill Vicars?

**Comment by daas-ankur-shukla** [comment]
Like any of these fonts for the heading SpeechToSign: https://www.elegantthemes.com/blog/resources/30-sans-serif-fonts-perfect-for-website-headings

**Comment by daas-ankur-shukla** [comment]
Any suggestion on the default image we use? I think a good gif of Prof. Bill will be good. What say?

**Comment by bneogy92** [comment]
A note of gratitude for Dr. William G. Vicars , Associate Professor, American Sign Language and Deaf Studies, California State University, for all the support.  Can be compressed possibly!

**Comment by daas-ankur-shukla** [comment]
I was thinking to somehow indicate that the face appearing is his. ?

**Comment by bneogy92** [comment]
Can we speak about that in the video and just thank him in the front end?

**Comment by bneogy92** [comment]
Bebas Neue as font looks good.
